### ISSUE TITLE
AcceptLanguageParserTest is in failure 

### ISSUE THREAD

**Issue by JordanTerri** [usnistgov/jsip#74]
The test doesn't pass when executed.

```
start gov.nist.javax.sip.parser.AcceptLanguageParserTest
Accept-Language:  da   
Encoded header = Accept-Language: da

Accept-Language: 
Encoded header = Accept-Language: 

Accept-Language: ,
Encoded header = Accept-Language: 

done gov.nist.javax.sip.parser.AcceptLanguageParserTest


testParser(gov.nist.javax.sip.parser.AcceptLanguageParserTest)  Time elapsed: 0.02 sec  <<< FAILURE!
junit.framework.AssertionFailedError: expected:<Accept-Language: 
> but was:<Accept-Language: 
>
	at junit.framework.Assert.fail(Assert.java:57)
	at junit.framework.Assert.failNotEquals(Assert.java:329)
```

**Comment by vladimirralev** [comment]
I'll check it out

**Comment by balgillo** [comment]
It looks like `AcceptLanguageParser.parse` creates an `AcceptLanguageList` containing two empty `AcceptLanguage` objects (i.e. with `languageRange == null`) from this string:
```
Accept-Language: ,\n
```
Then the test converts that back to a string using `((SIPHeader) hdr.clone()).encode().trim() + "\n"` and gets this different string:
```
Accept-Language:\n
```
This is then parsed to get an `AcceptLanguageList` containing one empty `AcceptLanguage` object, which does not match the first `AcceptLanguageList` which had two of them.

So, one of the following is correct:
- Empty languages should not be added to the accept list -> `AcceptLanguageParser` needs to change to ignore them, and `ParserTestCase.testParser` should not expect that "List should contain at least 1 header"
- At most one empty language should be added to the accept list ->  `AcceptLanguageParser` needs to change to ignore all but the first empty language that is added
- Any number of empty languages is allowed, and the number of empty languages should be preserved during encoding -> `gov.nist.javax.sip.header.SIPHeaderList.encodeBody(StringBuilder)` needs to change to add a comma even if `buffPosDelta == 0`
