### ISSUE TITLE
TCP IOException during INVITE results in not cleaned up dialogs

### ISSUE THREAD

**Issue by Domo42** [usnistgov/jsip#8]
Hello,

I've run into an issue where after TCP IO exceptions, dialogs are not cleaned up. As a result, memory is accumulated until the process runs out of memory.
I'm using version v1.2.301 of jain-sip-ri. This issue is reproducible in my environment.

To reproduce it I try to send an INVITE to a TCP target that does not exist. This results in an exception looking like this:
```
javax.sip.SipException: Could not connect to /10.42.42.42:5060
    at gov.nist.javax.sip.stack.SIPClientTransactionImpl.sendRequest(SIPClientTransactionImpl.java:1069)
    at com.company.ps.media.sip.MessageSendingService.sendRequest(MessageSendingService.java:69)
    at com.company.ps.media.sip.MessageSendingService.sendNewClientTransactionRequest(MessageSendingService.java:91)
    at com.company.ps.b2bua.common.MessageSendingServiceWrapper.lambda$sendNewClientTransactionRequest$2(MessageSendingServiceWrapper.java:71)
    at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source)
    at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
    at java.util.concurrent.FutureTask.run(Unknown Source)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)
Caused by: java.io.IOException: Could not connect to /10.42.42.42:5060
    at gov.nist.javax.sip.stack.IOHandler.sendBytes(IOHandler.java:391)
    at gov.nist.javax.sip.stack.TCPMessageChannel.sendMessage(TCPMessageChannel.java:350)
    at gov.nist.javax.sip.stack.MessageChannel.sendMessage(MessageChannel.java:281)
    at gov.nist.javax.sip.stack.SIPTransactionImpl.sendMessage(SIPTransactionImpl.java:892)
    at gov.nist.javax.sip.stack.SIPClientTransactionImpl.sendMessage(SIPClientTransactionImpl.java:475)
    at gov.nist.javax.sip.stack.SIPClientTransactionImpl.sendRequest(SIPClientTransactionImpl.java:1062)
    ... 11 more
```

The exception reporting the connection error is fine. The problem is that the created dialog is never cleaned up. What happens is for dialog instances to keep getting added into the ```SipStackImpl.earlyDialogTable``` where they are never removed.

From what I can gather, it seems to be a related with the _dialogState_ itself which is still at its initial value NULL_STATE (-1) after the exception and not changed at any later point in time.

My expectation would be that it if a dialog can not be established for any reason (regardless of transport) it is cleaned up after some time and all references to it are removed.

**Comment by vladimirralev** [comment]
Thanks. Got some general sample code to reproduce it?

**Comment by Domo42** [comment]
Not right now. It's currently embedded into a bigger code base.
I'll try to extract it, shoudn't be that hard.

**Comment by vladimirralev** [comment]
OK. Keep in mind that it's probably not going to be possible to clean up a dialog automatically in all cases here. It's too app-specific how to deal with failed connections. Especially if you are in the middle of a dialog, we can't just delete it if transport fails since you may want to retry the transport later and how much later is app-specific. Your application is in much better position to determine when deleting a dialog is appropriate.

Also please make sure you wait enough time for the ``gov.nist.javax.sip.EARLY_DIALOG_TIMEOUT_SECONDS`` to clean up leaking dialogs (180 seconds default) and that it fails to protect you.

**Comment by Domo42** [comment]
The things is, we are not in the middle of a dialog. I would not expect the dialog to be deleted if it is active for example. In my case the dialog was never established as the intial transaction failed.

Regarding the early dialog timeout. This seems to be unrelated. In the heap dumps I can still see the dialog instances within _SipStackImpl_ after 30 minutes and later.

**Comment by Domo42** [comment]
I've created a sample to reproduce it.
https://gist.github.com/Domo42/5c05815c0eaecfb33138e7db70283270

While the dialog references are stored in the _earlyDialogTable_, the state of the dialog itself is still NULL_STATE. There's no EarlyStateTask which might trigger the dialog error event and the deletion of the dialog itself.

**Comment by jagliot** [comment]
This change broke my implementation of a DNS retrying sip client transaction. By closing the dialog, it prevented me from reusing it in subsequent transaction (used to try on other dns records). I've made Uninitialized dialog leak fix usnistgov#8 change optional with the default being enabled. This enables me to disable the dialog termination when needed.

**Comment by vladimirralev** [comment]
Can you outline the changes since the commit here https://github.com/usnistgov/jsip/commit/23a33118405040ff93180102f4bd9beb3130c7c1 overwrites the whole file and it's hard to spot what changed? It's always best to keep diffs minified to spot changes quickly.

**Comment by jagliot** [comment]
Line endings in git is a plague.... I'll be more careful next commit.

Here are my changes:

line 233 added:
private boolean terminateDialogOnCleanUp = true;

wrapped line ~1930-1936 with an if:
 if (terminateDialogOnCleanUp) {
      // If dialog is null state, no response is received and we should clean it up now, 
      // it's hopeless to recover. Refers to this issue https://github.com/usnistgov/jsip/issues/8
      if(this.defaultDialog != null && this.defaultDialog.getState() == null) {
      	this.defaultDialog.setState(SIPDialog.TERMINATED_STATE);
      }
    }

added a setter at the end of the file:

  /**
   * @see gov.nist.javax.sip.stack.SIPClientTransaction#setTerminateDialogOnCleanUp(boolean)
   */
  public void setTerminateDialogOnCleanUp(boolean enabled) {
    terminateDialogOnCleanUp = enabled;
  }

**Comment by vladimirralev** [comment]
I see now. Thanks.
